### ISSUE TITLE
CT: Did not find matching Node

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/make-a-ten#287]
```
make-a-ten : fuzz : built : run
Uncaught TypeError: Cannot read property 'findAttachableNodes' of undefined
TypeError: Cannot read property 'findAttachableNodes' of undefined
    at e.tryToCombineNumbers (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/build/phet/make-a-ten_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:1307:690321)
    at end [as _end] (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/build/phet/make-a-ten_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:1307:651625)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/build/phet/make-a-ten_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:1307:647108
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/build/phet/make-a-ten_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:1307:519220)
    at emit1 (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/build/phet/make-a-ten_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:1307:23550)
    at e.release (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/build/phet/make-a-ten_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:1307:520818)
    at e.release (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/build/phet/make-a-ten_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:1307:647050)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/build/phet/make-a-ten_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:1307:517915)
    at e.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/build/phet/make-a-ten_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:1307:1304260)
    at e.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/build/phet/make-a-ten_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:1307:1303966)
Approximately 10/3/2018, 4:53:49 AM
make-a-ten : fuzz : require.js : run
Uncaught Error: Assertion failed: Did not find matching Node
Error: Assertion failed: Did not find matching Node
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/assert/js/assert.js:22:13)
    at MakeATenExploreScreenView.findPaperNumberNode (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js?bust=1538568235235:151:17)
    at MakeATenExploreScreenView.tryToCombineNumbers (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js?bust=1538568235235:162:30)
    at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/js/make-a-ten/common/view/PaperNumberNode.js?bust=1538568235235:91:9)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/DragListener.js?bust=1538568235235:274:27
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/PressListener.js?bust=1538568235235:332:19)
    at Emitter.emit1 (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/axon/js/Emitter.js?bust=1538568235235:157:52)
    at DragListener.release (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/PressListener.js?bust=1538568235235:515:29)
    at DragListener.release (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/DragListener.js?bust=1538568235235:270:39)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/PressListener.js?bust=1538568235235:210:14)
Approximately 10/3/2018, 4:53:49 AM
make-a-ten : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: Did not find matching Node
Error: Assertion failed: Did not find matching Node
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/assert/js/assert.js:22:13)
    at MakeATenExploreScreenView.findPaperNumberNode (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js?bust=1538567516370:151:17)
    at MakeATenExploreScreenView.tryToCombineNumbers (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js?bust=1538567516370:162:30)
    at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/js/make-a-ten/common/view/PaperNumberNode.js?bust=1538567516370:91:9)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/DragListener.js?bust=1538567516370:274:27
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/PressListener.js?bust=1538567516370:332:19)
    at Emitter.emit1 (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/axon/js/Emitter.js?bust=1538567516370:157:52)
    at DragListener.release (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/PressListener.js?bust=1538567516370:515:29)
    at DragListener.release (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/DragListener.js?bust=1538567516370:270:39)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/PressListener.js?bust=1538567516370:210:14)
Approximately 10/3/2018, 4:53:49 AM
make-a-ten : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: Did not find matching Node
Error: Assertion failed: Did not find matching Node
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/assert/js/assert.js:22:13)
    at MakeATenExploreScreenView.findPaperNumberNode (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js?bust=1538569926081:151:17)
    at MakeATenExploreScreenView.tryToCombineNumbers (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js?bust=1538569926081:162:30)
    at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/make-a-ten/js/make-a-ten/common/view/PaperNumberNode.js?bust=1538569926081:91:9)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/DragListener.js?bust=1538569926081:274:27
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/PressListener.js?bust=1538569926081:332:19)
    at Emitter.emit1 (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/axon/js/Emitter.js?bust=1538569926081:157:52)
    at DragListener.release (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/PressListener.js?bust=1538569926081:515:29)
    at DragListener.release (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/DragListener.js?bust=1538569926081:270:39)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1538564029953/scenery/js/listeners/PressListener.js?bust=1538569926081:210:14)
Approximately 10/3/2018, 4:53:49 AM
```

**Comment by jonathanolson** [comment]
I messed up a refactoring (PressListener change broke DragListener). Should be fixed now, can you confirm?

**Comment by KatieWoe** [comment]
Confirmed.
