### ISSUE TITLE
CT: Did not find matching Node

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/make-a-ten#292]
Possible from multitouch, caught in https://github.com/phetsims/aqua/issues/106. Steps to reproduce:

- Grab and drag a number with one finger.
- Press ResetAllButton with second finger.
- Release first finger from screen.

Assertion is "Assertion failed: Did not find matching Node".

**Comment by jessegreenberg** [comment]
I suspect that this will be fixed by DragListener of PaperNumberNode needs to be interrupted on simulation reset, but not sure. Assigning to responsible dev.

**Comment by KatieWoe** [comment]
Seen again 2/4/2021
```
make-a-ten : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/make-a-ten/make-a-ten_en.html?continuousTest=%7B%22test%22%3A%5B%22make-a-ten%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1612446304630%22%2C%22timestamp%22%3A1612449456336%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Uncaught Error: Assertion failed: Did not find matching Node
Error: Assertion failed: Did not find matching Node
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/assert/js/assert.js:25:13)
at MakeATenGameScreenView.findPaperNumberNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js:147:15)
at MakeATenGameScreenView.tryToCombineNumbers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js:158:30)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/make-a-ten/js/make-a-ten/common/view/PaperNumberNode.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/scenery/js/listeners/DragListener.js:338:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/scenery/js/listeners/PressListener.js:646:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/axon/js/Action.js:225:18)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/scenery/js/listeners/PressListener.js:427:25)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/scenery/js/listeners/DragListener.js:334:11)
at DragListener.pointerUp (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612446304630/scenery/js/listeners/PressListener.js:757:12)
id: Bayes Chrome
Snapshot from 2/4/2021, 6:45:04 AM
```

**Comment by pixelzoom** [comment]
In 2/4/21 dev meeting, we established that this may be due to CT multi-touch fuzz testing ( ?fuzzPointers=2) being enabled for phetsims/aqua#106.

**Comment by pixelzoom** [comment]
Still occurring as of 4/6/2021, 7+ months after first reported.

**Comment by marlitas** [comment]
I fuzzed this sim for 10 minutes with `fuzzPointers=2` and also checked the last 40 columns of CT. It is nowhere to be found. I'm closing it as stale, but feel free to re-open if it comes back.
