### ISSUE TITLE
CT: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/make-a-ten#293]
Based on the timing of when this error started occurring, I suspect that it's related to the conversion of ScreenView subtypes to ES6 `class` for https://github.com/phetsims/tasks/issues/1044.

```
make-a-ten : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602551898160/make-a-ten/make-a-ten_en.html?continuousTest=%7B%22test%22%3A%5B%22make-a-ten%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1602551898160%22%2C%22timestamp%22%3A1602552510558%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'apply' of undefined
TypeError: Cannot read property 'apply' of undefined
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602551898160/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602551898160/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602551898160/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602551898160/axon/js/Emitter.js:60:19)
at DragListener.start [as _start] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602551898160/make-a-ten/js/make-a-ten/common/view/PaperNumberNode.js:78:38)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602551898160/scenery/js/listeners/DragListener.js:303:27
at DragListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602551898160/scenery/js/listeners/PressListener.js:596:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602551898160/axon/js/Action.js:225:18)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602551898160/scenery/js/listeners/PressListener.js:391:23)
at DragListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602551898160/scenery/js/listeners/DragListener.js:280:51)
id: Bayes Chrome
Snapshot from 10/12/2020, 7:18:18 PM
```

**Comment by pixelzoom** [comment]
I fuzzed each screen separately using `?screens`, and the error is occurring in the "Explore" screen (`?screens=1`).

Rolling back `MakeATenExploreScreenView` and `MakeATenCommonView` (the superclass) to their `inherit` implementations confirms that the problem goes away.

**Comment by pixelzoom** [comment]
I really don't understand what's going wrong here, and why it's manifesting in `PaperNumberNode`.  I suspect this is another case where we need to use `this` before calling `super`.     To quiet CT, I rolled back `MakeATenExploreScreenView` and `MakeATenCommonView` to their inherit implementations in the above commit. 

@jonathanolson would you mind converting `MakeATenExploreScreenView` and `MakeATenCommonView` to ES6 `class`?

**Comment by jonathanolson** [comment]
Was calling subtype-overridden methods before they could use their subtype fields (apparently you can do `emitter.addListener( undefined )` without errors now?)

Back to you.

**Comment by pixelzoom** [comment]
Thanks! Closing.
