### ISSUE TITLE
CT cannot read property getOriginPosition of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/make-a-ten#300]
```
make-a-ten : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628503838038/make-a-ten/make-a-ten_en.html?continuousTest=%7B%22test%22%3A%5B%22make-a-ten%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1628503838038%22%2C%22timestamp%22%3A1628520302213%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read property 'getOriginPosition' of undefined
TypeError: Cannot read property 'getOriginPosition' of undefined
at MakeATenExploreScreenView.onNumberDragFinished (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628503838038/make-a-ten/js/make-a-ten/explore/view/MakeATenExploreScreenView.js:231:98)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628503838038/axon/js/TinyEmitter.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628503838038/axon/js/Emitter.js:39:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628503838038/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628503838038/axon/js/Emitter.js:64:19)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628503838038/counting-common/js/common/view/PaperNumberNode.js:99:38)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628503838038/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628503838038/scenery/js/listeners/PressListener.js:680:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628503838038/axon/js/Action.js:227:18)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628503838038/scenery/js/listeners/PressListener.js:458:25)
id: Bayes Chrome
Snapshot from 8/9/2021, 4:10:38 AM
```

**Comment by marlitas** [comment]
The last 40 columns of `make-a-ten` are clear. Closing as stale.
