### ISSUE TITLE
CT center should be a finite Vector2

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/make-a-ten#307]
```
make-a-ten : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675166447047/make-a-ten/make-a-ten_en.html?continuousTest=%7B%22test%22%3A%5B%22make-a-ten%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1675166447047%22%2C%22timestamp%22%3A1675169303458%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: center should be a finite Vector2
Error: Assertion failed: center should be a finite Vector2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675166447047/assert/js/assert.js:28:13)
at assert (Node.ts:3312:14)
at setCenter (Node.ts:3326:9)
at (CountingCreatorNode.ts:141:8)
at callback (Multilink.ts:128:6)
at (Multilink.ts:184:11)
at multilink (CountingCreatorNode.ts:124:14)
at (ExplorePanel.js:35:30)
at (MakeATenExploreScreenView.js:68:24)
at (MakeATenExploreScreen.js:33:15)
id: Bayes Puppeteer
Snapshot from 1/31/2023, 5:00:47 AM

----------------------------------

make-a-ten : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675166447047/make-a-ten/make-a-ten_en.html?continuousTest=%7B%22test%22%3A%5B%22make-a-ten%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1675166447047%22%2C%22timestamp%22%3A1675169518479%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: center should be a finite Vector2
Error: Assertion failed: center should be a finite Vector2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675166447047/assert/js/assert.js:28:13)
at assert (Node.ts:3312:14)
at setCenter (Node.ts:3326:9)
at (CountingCreatorNode.ts:141:8)
at callback (Multilink.ts:128:6)
at (Multilink.ts:184:11)
at multilink (CountingCreatorNode.ts:124:14)
at (ExplorePanel.js:35:30)
at (MakeATenExploreScreenView.js:68:24)
at (MakeATenExploreScreen.js:33:15)
id: Bayes Puppeteer
Snapshot from 1/31/2023, 5:00:47 AM

----------------------------------

make-a-ten : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675166447047/make-a-ten/make-a-ten_en.html?continuousTest=%7B%22test%22%3A%5B%22make-a-ten%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1675166447047%22%2C%22timestamp%22%3A1675169411256%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: center should be a finite Vector2
Error: Assertion failed: center should be a finite Vector2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675166447047/assert/js/assert.js:28:13)
at assert (Node.ts:3312:14)
at setCenter (Node.ts:3326:9)
at (CountingCreatorNode.ts:141:8)
at callback (Multilink.ts:128:6)
at (Multilink.ts:184:11)
at multilink (CountingCreatorNode.ts:124:14)
at (ExplorePanel.js:35:30)
at (MakeATenExploreScreenView.js:68:24)
at (MakeATenExploreScreen.js:33:15)
id: Bayes Puppeteer
Snapshot from 1/31/2023, 5:00:47 AM

----------------------------------

make-a-ten : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675166447047/make-a-ten/make-a-ten_en.html?continuousTest=%7B%22test%22%3A%5B%22make-a-ten%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1675166447047%22%2C%22timestamp%22%3A1675170543821%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: center should be a finite Vector2
Error: Assertion failed: center should be a finite Vector2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675166447047/assert/js/assert.js:28:13)
at assert (Node.ts:3312:14)
at setCenter (Node.ts:3326:9)
at (CountingCreatorNode.ts:141:8)
at callback (Multilink.ts:128:6)
at (Multilink.ts:184:11)
at multilink (CountingCreatorNode.ts:124:14)
at (ExplorePanel.js:35:30)
at (MakeATenExploreScreenView.js:68:24)
at (MakeATenExploreScreen.js:33:15)
id: Bayes Puppeteer
Snapshot from 1/31/2023, 5:00:47 AM
```

**Comment by veillette** [comment]
The problem lies in `CountingCreatorNode` . 

In the following line we try to center the node.

```js
        // recenter ourselves after we change the bounds of the front and back targets
        this.center = options.creatorNodeBackground.selfBounds.center;
```

but by default we have for `options.creatorNodeBackground`

```js
    const options = optionize<CountingCreatorNodeOptions, SelfOptions, NodeOptions>()( {
   ...
      creatorNodeBackground: new Node()
    }, providedOptions );
```

I suspect that the default is invoked, in which case there is not a center for an empty Node.

**Comment by veillette** [comment]
Assigning @chrisklus since it is related to some of his work.

**Comment by chrisklus** [comment]
Thanks @KatieWoe and @veillette! This should be all set now, MAT is running well on my end. Closing.
